name: pull-request-verification

on:
  pull_request:
    branches: [development]
    
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: artiomtr/jest-coverage-report-action@v1.3
              
