name: pull-request-verification

on:
  push:
    branches:
      - "*"
    
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: artiomtr/jest-coverage-report-action@v1.3
              
